"""migration

Revision ID: 2394eb8be9d3
Revises: 7b2309b943a9
Create Date: 2024-10-02 18:04:13.352627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2394eb8be9d3'
down_revision: Union[str, None] = '7b2309b943a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dietplan_dietitian_user_id'), 'dietplan', ['dietitian_user_id'], unique=False)
    op.create_index(op.f('ix_dietplan_user_id'), 'dietplan', ['user_id'], unique=False)
    op.create_foreign_key(None, 'dietplan', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'dietplan', 'user', ['dietitian_user_id'], ['user_id'])
    op.create_index(op.f('ix_permissions_role_id'), 'permissions', ['role_id'], unique=False)
    op.create_foreign_key(None, 'permissions', 'role', ['role_id'], ['role_id'])
    op.create_index(op.f('ix_usersroles_role_id'), 'usersroles', ['role_id'], unique=False)
    op.create_index(op.f('ix_usersroles_user_id'), 'usersroles', ['user_id'], unique=False)
    op.create_foreign_key(None, 'usersroles', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'usersroles', 'role', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usersroles', type_='foreignkey')
    op.drop_constraint(None, 'usersroles', type_='foreignkey')
    op.drop_index(op.f('ix_usersroles_user_id'), table_name='usersroles')
    op.drop_index(op.f('ix_usersroles_role_id'), table_name='usersroles')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_index(op.f('ix_permissions_role_id'), table_name='permissions')
    op.drop_constraint(None, 'dietplan', type_='foreignkey')
    op.drop_constraint(None, 'dietplan', type_='foreignkey')
    op.drop_index(op.f('ix_dietplan_user_id'), table_name='dietplan')
    op.drop_index(op.f('ix_dietplan_dietitian_user_id'), table_name='dietplan')
    # ### end Alembic commands ###
