"""initial migration

Revision ID: 7b2309b943a9
Revises: 
Create Date: 2024-10-02 10:01:02.793315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7b2309b943a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietplan',
    sa.Column('diet_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dietitian_user_id', sa.Integer(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('plan_status', sqlmodel.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('diet_plan_id')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sqlmodel.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sqlmodel.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.String(length=255), nullable=False),
    sa.Column('email', sqlmodel.String(length=255), nullable=False),
    sa.Column('gender', sqlmodel.String(length=10), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('diet_type', sqlmodel.String(length=20), nullable=False),
    sa.Column('password', sqlmodel.String(length=255), nullable=False),
    sa.Column('role', sqlmodel.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usersroles',
    sa.Column('users_roles_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('users_roles_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersroles')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('permissions')
    op.drop_table('dietplan')
    # ### end Alembic commands ###
